version: 2
jobs:
  build-deps:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - persist_to_workspace:
          root: /usr
          paths:
            - bin/*
  deploy-client:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: /usr
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t olavim/outliner-client:$TAG -f docker/client.Dockerfile .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push olavim/outliner-client:$TAG
  deploy-server:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: /usr
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t olavim/outliner-server:$TAG -f docker/server.Dockerfile .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push olavim/outliner-client:$TAG

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-deps
      - deploy-client:
          requires:
            - build-deps
          filters:
            branches:
              only: server
      - deploy-server:
          requires:
            - build-deps
          filters:
            branches:
              only: server
