version: 2
jobs:
  build-deps:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Transpile sources
          command: yarn run build
      - persist_to_workspace:
          root: dist
          paths: client
  deploy-gh-pages:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages
            git config user.email "tilastokeskus@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "1c:2c:a5:02:39:28:5c:ea:7d:b5:2c:55:20:df:6f:11"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" --dist dist/client

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-deps
      - deploy-gh-pages:
          requires:
            - build-deps
          filters:
            branches:
              only: master