version: 2
jobs:
  build-client:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build client Docker image
          command: docker build -t olavim/outliner-client:1.0.$CIRCLE_BUILD_NUM -f docker/client.Dockerfile .
  build-server:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build server Docker image
          command: docker build -t olavim/outliner-server:1.0.$CIRCLE_BUILD_NUM -f docker/server.Dockerfile .
  deploy-client:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish client Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            docker push olavim/outliner-client:1.0.$CIRCLE_BUILD_NUM
  deploy-server:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish server Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            docker push olavim/outliner-server:1.0.$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-deps
      - deploy-client:
          requires:
            - build-client
          filters:
            branches:
              only: server
      - deploy-server:
          requires:
            - build-server
          filters:
            branches:
              only: server
